query homePage($filter: PostFilter) {
  page(relativePath: "homepage.mdx") {
    ...PageParts
  }

  postConnection(sort: "date", filter: $filter, last: 5) {
    edges {
      node {
        title
        date
        id
        _sys {
          filename
        }
      }
    }
  }
}
